### ISSUE TITLE
SSH Support

### ISSUE THREAD

**Issue by wparad** [fusebit/cloud-git#1]
Who uses HTTPS for git? ;p. Obviously SSH support is necessary to be a viable solution to interact with actual users. I can see for an internal service HTTP works but we would need TCP packet handling and SSH to make it viable.

**Comment by JasonWoof** [comment]
hehe, good one. Let's see: github uses https. It's the default, and if you're not logged into github then they won't even generate the ssh url for you.

ssh would be a cool feature, though I'm not sure how that should work. I don't think an ssh implementation in node.js would be a good idea.

I just discovered this project today. Seems cool. I'm researching the feasibility of making a CMS where you can push/pull the data with git. It would be very cool if my clients could use the admin panel on the website and I could use git/vscode and we could all get along. Also they could get efficient backups.

too bad there were only commits in a 4-day window last year.

**Comment by bennbollay** [comment]
Feel free to file any bug requests you might have, @JasonWoof.  We're paying attention :)

There's no plan to currently implement ssh within node as part of this project.
